title: Yongming Xiong's Homepage
page-top-title: Yongming Xiong
top-section-bg-text: Engineering 
home-subtitle: Yongming Xiong&ensp;|&ensp;熊永明
copyright-text: '&copy; Yongming Xiong 2023-2024. All Rights Reserved.'
